#!/bin/bash
# Setup script to install git hooks that remove AI attribution from commits
# Run this after cloning the repository

HOOKS_DIR=".git/hooks"

echo "Setting up git hooks to remove AI attribution from commits..."

# Create prepare-commit-msg hook
cat > "$HOOKS_DIR/prepare-commit-msg" << 'EOF'
#!/bin/bash
# Git hook to remove AI/Claude attribution from commit messages
# This prevents AI tool signatures from appearing in commit history

COMMIT_MSG_FILE="$1"
COMMIT_SOURCE="$2"

# Only process if this is a regular commit (not merge, etc.)
if [ -z "$COMMIT_SOURCE" ] || [ "$COMMIT_SOURCE" = "message" ]; then
    # Remove Claude Code attribution footer
    sed -i '/🤖 Generated with \[Claude Code\]/d' "$COMMIT_MSG_FILE"
    sed -i '/Co-Authored-By: Claude <noreply@anthropic.com>/d' "$COMMIT_MSG_FILE"
    sed -i '/Generated with Claude Code/d' "$COMMIT_MSG_FILE"
    sed -i '/Co-Authored-By: Claude/d' "$COMMIT_MSG_FILE"

    # Remove other AI tool signatures
    sed -i '/Generated by AI/d' "$COMMIT_MSG_FILE"
    sed -i '/Co-Authored-By: AI/d' "$COMMIT_MSG_FILE"

    # Clean up excessive blank lines at the end
    perl -i -pe 'chomp if eof' "$COMMIT_MSG_FILE"
fi

exit 0
EOF

# Create commit-msg hook
cat > "$HOOKS_DIR/commit-msg" << 'EOF'
#!/bin/bash
# Git hook to remove AI/Claude attribution from commit messages
# This ensures clean, professional commits without AI tool traces

COMMIT_MSG_FILE="$1"

# Remove Claude Code attribution and co-author lines
sed -i '/🤖 Generated with \[Claude Code\]/d' "$COMMIT_MSG_FILE"
sed -i '/Co-Authored-By: Claude <noreply@anthropic.com>/d' "$COMMIT_MSG_FILE"
sed -i '/Generated with Claude Code/d' "$COMMIT_MSG_FILE"
sed -i '/Co-Authored-By: Claude/d' "$COMMIT_MSG_FILE"

# Remove trailing empty lines
sed -i -e :a -e '/^\s*$/d;N;ba' "$COMMIT_MSG_FILE"

exit 0
EOF

# Make hooks executable
chmod +x "$HOOKS_DIR/prepare-commit-msg"
chmod +x "$HOOKS_DIR/commit-msg"

echo "✓ Git hooks installed successfully!"
echo ""
echo "The following hooks are now active:"
echo "  - prepare-commit-msg: Removes AI attribution before commit"
echo "  - commit-msg: Secondary cleanup of AI attribution"
echo ""
echo "Your commits will now be clean of AI tool traces."
