AortaCFD-app/
│
├── .gitignore            # To ignore unwanted files/folders
│
├── README.md             # Project description, setup instructions, etc.
│
├── LICENSE               # Open source license file
│
├── CAD/           # Directory for your raw geometry files
│   ├── geometry*/
│   │   ├── inlet.stl
│   │   ├── outlet1.stl
│   │   ├── outlet2.stl
│   │   ├── outlet3.stl
│   │   ├── outlet4.stl
│   │   ├── wall_aorta.stl
|
├── OPENFOAM_CASES/
│   ├── geometry*/         # OpenFOAM cases for each geometry
│   │   ├── 0/
│   │   │   ├── U
│   │   │   ├── p
│   │   │   └── ...
│   │   ├── constant/
│   │   │   ├── transportProperties
│   │   │   ├── momentumTransport
│   │   ├── |── windkesselProperties
│   │   ├── |── boundaryData  # Boundary conditions
│   │   |   |   |── inlet
│   │   |   |   |   ├── points # Inlet points
│   │   |   |   |   ├── inletBCs # Inlet boundary conditions one cycle
│   │   |   |   |   |   ├── U_0 
│   │   |   |   |   |   ├── U_1
│   │   |   |   |   ├── U_0 # symbolic link to U_0
│   │   |   |   |   ├── U_1 # symbolic link to U_1
│   │   |   |   |   ├── ...
│   │   │   └── ...
│   │   ├── system/
│   │   │   ├── controlDict
│   │   │   ├── fvSchemes
│   │   │   ├── fvSolution
│   │   │   └── ...
│   │   └── ...
│
├── SCRIPTS/
│   ├── boundaryConditionSetup.py
│   ├── cycleDataSetup.py
│   ├── formatPoints.py
│   ├── simulationSetup.py  
│   └── ...
│
├── container/             # Docker or Singularity files for HPC/Cloud
│   ├── Dockerfile
│   ├── singularity.def
│   └── ...
│
└── docs/                  # Documentation other than README
    ├── setup.md
    ├── simulation.md
    └── ...