AortaCFD-app/
│
├── .gitignore            # To ignore unwanted files/folders
│
├── README.md             # Project description, setup instructions, etc.
│
├── LICENSE               # Open source license file
│
├── CAD/           # Directory for your raw geometry files
│   ├── geometry*/
│   │   ├── inlet.stl
│   │   ├── outlet1.stl
│   │   ├── outlet2.stl
│   │   ├── outlet3.stl
│   │   ├── outlet4.stl
│   │   ├── wall_aorta.stl
|
├── MESH/
│   ├── blockMeshDicts/   # blockMesh dictionaries for each geometry
│   │   ├── geometry*
│   │
│   ├── snappyHexMeshDicts/ # snappyHexMesh dictionaries for refinements
│       ├── coarse/
│       ├── medium/
│       ├── fine/
│
├── appDriver/
│   ├── appDriver.py      # Main script to run the app
│   |   ├── create_OFcase
│   |   |   ├── system/
|   |   |   |   ├── controlDict
|   |   |   |   ├── decomposeParDict
|   |   |   |   ├── fvSchemes
|   |   |   |   ├── fvSolution
|   |   |   |   ├── blockMeshDict
|   |   |   |   ├── snappyHexMeshDict
|   |   |   |   ├── ...
│   |   |   ├── constant/
|   |   |   |   ├── transportProperties
|   |   |   |   ├── momentumTransport/
|   |   |   |   ├── windkesselProperties/
|   |   |   |   ├── boundaryConditions*/
|   |   |   |   |   ├── inlet/
|   |   |   |   |   ├── points
|   |   |   |   ├── triSurface/
|   |   |   |   ├── ...
│   |   |   ├── initial_conditions/
│   │   |   |   ├── U/
│   │   |   |   ├── p/
│   │   |   |   ├── nut/
|   |   |   |   ├── ...
│
├── SCRIPTS/
│   ├── meshSetup.py
│   ├── boundaryConditionsSetup.py
│   ├── physicalPropertiesSetup.py
│   ├── numericalPropertiesSetup.py
│   ├── solverSetup.py
|   ├── simulationSetup.py
|   ├── inletMapping.py
|   ├── inletDataSetup.py
|   ├── solnTypeSetup.py
|   ├── wkSetup.py
│
├── POSTPro/
│   ├── pvbatch_scripts/   # Paraview pvbatch scripts for post-processing
|   |   ├── phaseAverage
│   │   ├── contour.py
│   │   ├── streamline.py
│   │   ├── 
│   │
│   ├── data/    # Place for generated visualizations
│   └── images/     # Extracted data from post processing
│
├── container/             # Docker or Singularity files for HPC/Cloud
│   ├── Dockerfile
│   ├── singularity.def
│   └── ...
│
└── docs/                  # Documentation other than README
    ├── setup.md
    ├── usage.md
    ├── results.md
    └── ...
