/*--------------------------------*- C++ -*----------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Version:  {{ config.openfoam_version }}
     \\/     M anipulation  |
\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "system";
    object      snappyHexMeshDict;
}
// ************************************************************************* //
// Generated by AortaCFD - Optimized for cardiovascular geometries
// All defaults sourced from base.py (single source of truth)
// Ref: OpenFOAM documentation (openfoam.com/documentation/guides/latest)
// ************************************************************************* //

castellatedMesh {{ config.mesh.SNAPPY_SETTINGS.castellatedMesh | string | lower }};
snap            {{ config.mesh.SNAPPY_SETTINGS.snap | string | lower }};
addLayers       {{ config.mesh.SNAPPY_SETTINGS.addLayers | string | lower }};

geometry
{
    {% for patch_name in patches %}
    "{{ patch_name }}.stl"
    {
        type triSurfaceMesh;
        file "{{ patch_name }}.stl";
        name {{ patch_name }};
    }
    {% endfor %}

    {% if bounding_box_refine_level and bounding_box_refine_level > 0 %}
    // Bounding box for two-stage refinement (coarse blockMesh + snappy refinement)
    geometryRefinementBox
    {
        type searchableBox;
        min ({{ '%.6g' % geometry_bbox.min[0] }} {{ '%.6g' % geometry_bbox.min[1] }} {{ '%.6g' % geometry_bbox.min[2] }});
        max ({{ '%.6g' % geometry_bbox.max[0] }} {{ '%.6g' % geometry_bbox.max[1] }} {{ '%.6g' % geometry_bbox.max[2] }});
    }
    {% endif %}
};

// ==========================================================================
// CASTELLATED MESH CONTROLS
// Ref: guide-meshing-snappyhexmesh-castellation.html
// ==========================================================================
castellatedMeshControls
{
    // Cell count limits
    maxLocalCells       {{ config.mesh.SNAPPY_SETTINGS.maxLocalCells }};
    maxGlobalCells      {{ config.mesh.SNAPPY_SETTINGS.maxGlobalCells }};
    minRefinementCells  {{ config.mesh.SNAPPY_SETTINGS.minRefinementCells }};
    maxLoadUnbalance    {{ config.mesh.SNAPPY_SETTINGS.maxLoadUnbalance }};

    // Refinement transition smoothness (OpenFOAM recommended: 3)
    nCellsBetweenLevels {{ config.mesh.SNAPPY_SETTINGS.nCellsBetweenLevels }};

    // Feature edges from eMesh files
    features
    (
        {% for patch_name in patches %}
        {
            file "{{ patch_name }}.eMesh";
            {# Feature level: use explicit value or auto-calculate from max surface refinement #}
            {% set surface_levels = config.mesh.SNAPPY_SETTINGS.surfaceRefinementLevels %}
            {% set auto_feature_level = surface_levels[1] if surface_levels|length > 1 else surface_levels[0] %}
            level {{ config.mesh.SNAPPY_SETTINGS.get('featureLevel', auto_feature_level) }};
        }
        {% endfor %}
    );

    // Surface refinement levels [min, max]
    refinementSurfaces
    {
        {% for patch_name in patches %}
        {{ patch_name }}
        {
            level ({{ config.mesh.SNAPPY_SETTINGS.surfaceRefinementLevels[0] }} {{ config.mesh.SNAPPY_SETTINGS.surfaceRefinementLevels[1] }});
        }
        {% endfor %}
    }

    // Volume-based refinement regions
    refinementRegions
    {
    {% if bounding_box_refine_level and bounding_box_refine_level > 0 %}
        // Two-stage mesh refinement: bounding box for fine meshes
        geometryRefinementBox
        {
            mode            inside;
            levels          (({{ bounding_box_refine_level }} {{ bounding_box_refine_level }}));
        }
    {% endif %}
    {% if config.mesh.SNAPPY_SETTINGS.get('span_refinement_enabled', False) %}
        // Span-based refinement for narrow regions (coarctations, stenoses)
        // Guarantees minimum cells across vessel diameter
        {{ wall_patch }}
        {
            mode            insideSpan;
            level           ({{ config.mesh.SNAPPY_SETTINGS.get('span_refinement_distance', 1000) }} {{ config.mesh.SNAPPY_SETTINGS.get('span_refinement_level', 2) }});
            cellsAcrossSpan {{ config.mesh.SNAPPY_SETTINGS.get('cells_across_span', 20) }};
        }
    {% endif %}
    }

    locationInMesh ({{ '%.6g' % internal_point[0] }} {{ '%.6g' % internal_point[1] }} {{ '%.6g' % internal_point[2] }});
    allowFreeStandingZoneFaces true;

    // Feature resolution angle - triggers higher refinement at sharp features
    resolveFeatureAngle {{ config.mesh.SNAPPY_SETTINGS.resolveFeatureAngle }};
};

// ==========================================================================
// SNAP CONTROLS
// Ref: guide-meshing-snappyhexmesh-snapping.html
// ==========================================================================
snapControls
{
    // Surface smoothing before snapping
    nSmoothPatch        {{ config.mesh.SNAPPY_SETTINGS.nSmoothPatch }};
    nSmoothInternal     {{ config.mesh.SNAPPY_SETTINGS.nSmoothInternal }};

    // Snap attraction distance (multiplied by local cell-edge length)
    tolerance           {{ config.mesh.SNAPPY_SETTINGS.snapTolerance }};

    // Mesh displacement solver iterations
    nSolveIter          {{ config.mesh.SNAPPY_SETTINGS.nSolveIter }};

    // Snapping relaxation iterations
    nRelaxIter          {{ config.mesh.SNAPPY_SETTINGS.nRelaxIter }};

    // Feature edge snapping iterations
    nFeatureSnapIter    {{ config.mesh.SNAPPY_SETTINGS.nFeatureSnapIter }};

    // Feature snap modes
    implicitFeatureSnap {{ config.mesh.SNAPPY_SETTINGS.implicitFeatureSnap | string | lower }};
    explicitFeatureSnap {{ config.mesh.SNAPPY_SETTINGS.explicitFeatureSnap | string | lower }};
    multiRegionFeatureSnap {{ config.mesh.SNAPPY_SETTINGS.multiRegionFeatureSnap | string | lower }};
};

// ==========================================================================
// ADD LAYERS CONTROLS
// Ref: guide-meshing-snappyhexmesh-layers.html
// Critical for WSS accuracy in cardiovascular CFD (target y+ ≈ 1)
// ==========================================================================
addLayersControls
{
    // Layer sizing mode: true = relative to cell size, false = absolute meters
    relativeSizes       {{ config.mesh.SNAPPY_SETTINGS.relativeSizes | string | lower }};

    // Patch-specific layer configuration
    layers
    {
        "{{ wall_patch }}"
        {
            nSurfaceLayers {{ config.mesh.SNAPPY_SETTINGS.addLayer }};
        }
    }

    // Layer growth parameters
    expansionRatio      {{ config.mesh.SNAPPY_SETTINGS.expansionRatio }};
    {% if config.mesh.SNAPPY_SETTINGS.get('firstLayerThickness') is not none %}
    firstLayerThickness {{ config.mesh.SNAPPY_SETTINGS.firstLayerThickness }};
    {% else %}
    finalLayerThickness {{ config.mesh.SNAPPY_SETTINGS.finalLayerThickness }};
    {% endif %}
    minThickness        {{ config.mesh.SNAPPY_SETTINGS.minThickness }};

    // Feature angle controls (critical for curved surfaces)
    featureAngle        {{ config.mesh.SNAPPY_SETTINGS.featureAngle }};
    slipFeatureAngle    {{ config.mesh.SNAPPY_SETTINGS.slipFeatureAngle }};
    {% if config.mesh.SNAPPY_SETTINGS.get('layerTerminationAngle') is not none %}
    layerTerminationAngle {{ config.mesh.SNAPPY_SETTINGS.layerTerminationAngle }};
    {% endif %}

    // Growth controls
    nGrow               {{ config.mesh.SNAPPY_SETTINGS.nGrow }};
    nBufferCellsNoExtrude {{ config.mesh.SNAPPY_SETTINGS.nBufferCellsNoExtrude }};

    // Layer addition relaxation iterations
    nRelaxIter          {{ config.mesh.SNAPPY_SETTINGS.get('addLayers_nRelaxIter', 5) }};

    // Smoothing iterations (important for high curvature)
    nSmoothNormals      {{ config.mesh.SNAPPY_SETTINGS.nSmoothNormals }};
    nSmoothSurfaceNormals {{ config.mesh.SNAPPY_SETTINGS.nSmoothSurfaceNormals }};
    nSmoothThickness    {{ config.mesh.SNAPPY_SETTINGS.nSmoothThickness }};
    nSmoothDisplacement {{ config.mesh.SNAPPY_SETTINGS.nSmoothDisplacement }};

    // Thickness ratio controls (prevent self-intersection in narrow regions)
    maxFaceThicknessRatio {{ config.mesh.SNAPPY_SETTINGS.maxFaceThicknessRatio }};
    maxThicknessToMedialRatio {{ config.mesh.SNAPPY_SETTINGS.maxThicknessToMedialRatio }};
    minMedianAxisAngle  {{ config.mesh.SNAPPY_SETTINGS.minMedianAxisAngle }};

    // Iteration limits
    nLayerIter          {{ config.mesh.SNAPPY_SETTINGS.nLayerIter }};
    nRelaxedIter        {{ config.mesh.SNAPPY_SETTINGS.nRelaxedIter }};
}

// ==========================================================================
// MESH QUALITY CONTROLS
// Ref: guide-meshing-snappyhexmesh-meshquality.html
// Non-orthogonality correction guidelines:
//   < 65°: no correctors needed
//   65-75°: 1 corrector
//   > 85°: likely divergence
// ==========================================================================
meshQualityControls
{
    // Non-orthogonality (angle between cell center vector and face normal)
    maxNonOrtho         {{ config.mesh.SNAPPY_SETTINGS.maxNonOrtho }};

    // Skewness controls
    maxBoundarySkewness {{ config.mesh.SNAPPY_SETTINGS.maxBoundarySkewness }};
    maxInternalSkewness {{ config.mesh.SNAPPY_SETTINGS.maxInternalSkewness }};

    // Cell shape quality
    maxConcave          {{ config.mesh.SNAPPY_SETTINGS.maxConcave }};
    minVol              {{ config.mesh.SNAPPY_SETTINGS.minVol }};
    minTetQuality       {{ config.mesh.SNAPPY_SETTINGS.minTetQuality }};
    minArea             {{ config.mesh.SNAPPY_SETTINGS.minArea }};
    minTwist            {{ config.mesh.SNAPPY_SETTINGS.minTwist }};
    minDeterminant      {{ config.mesh.SNAPPY_SETTINGS.minDeterminant }};
    minFaceWeight       {{ config.mesh.SNAPPY_SETTINGS.minFaceWeight }};
    minVolRatio         {{ config.mesh.SNAPPY_SETTINGS.minVolRatio }};
    minTriangleTwist    {{ config.mesh.SNAPPY_SETTINGS.minTriangleTwist }};

    // Smoothing and error reduction
    nSmoothScale        {{ config.mesh.SNAPPY_SETTINGS.nSmoothScale }};
    errorReduction      {{ config.mesh.SNAPPY_SETTINGS.errorReduction }};

    // Relaxed constraints for layer addition phase
    // Applied after nRelaxedIter iterations to improve layer coverage
    relaxed
    {
        maxNonOrtho         {{ config.mesh.SNAPPY_SETTINGS.relaxed_maxNonOrtho }};
        maxBoundarySkewness {{ config.mesh.SNAPPY_SETTINGS.relaxed_maxBoundarySkewness }};
        maxInternalSkewness {{ config.mesh.SNAPPY_SETTINGS.relaxed_maxInternalSkewness }};
        {% if config.mesh.SNAPPY_SETTINGS.relaxed_minDeterminant is defined %}
        minDeterminant      {{ config.mesh.SNAPPY_SETTINGS.relaxed_minDeterminant }};
        {% endif %}
        {% if config.mesh.SNAPPY_SETTINGS.relaxed_minVol is defined %}
        minVol              {{ config.mesh.SNAPPY_SETTINGS.relaxed_minVol }};
        {% endif %}
    }
};

debug 0;

writeFlags
(
    scalarLevels
    layerSets
    layerFields
);

mergeTolerance {{ config.mesh.SNAPPY_SETTINGS.get('mergeTolerance', 1e-6) }};

// ************************************************************************* //
